storage:
  path: "/home/mawen/Documents/github/mawen12/logs-viewer/data/data.db"

sources:
  - name: "app.log"
    group: "local"
    source: "cmd://127.0.0.1:/Users/mawen/logs/app.log"
    pattern: "yyyy-MM-dd HH:mm:ss,SSS"
  - name: "single.log"
    group: "local"
    source: "cmd://127.0.0.1:/Users/mawen/logs/single.log"
    pattern: "yyyy-MM-dd HH:mm:ss,SSS"
  - name: "monitor.log"
    group: "local"
    source: "cmd://127.0.0.1:/Users/mawen/logs/monitor.log"
    pattern: "yyyy-MM-dd HH:mm:ss,SSS"
  # - name: "app.log"
  #   group: "remote"
  #   source: "ssh://root:admin@192.168.122.6:22:/root/logs/app.log"
  #   pattern: "yyyy-MM-dd HH:mm:ss,SSS"
  # - name: "bpp.log"
  #   group: "remote"
  #   source: "ssh://root:admin@192.168.122.6:22:/root/logs/bpp.log"      
  #   pattern: "yyyy-MM-dd HH:mm:ss,SSS"
  # - name: "monitor-stat.log"
  #   group: "remote"
  #   source: "ssh://root:admin@192.168.122.6:22:/root/logs/monitor-stat.log"  
  #   pattern: "yyyy-MM-dd HH:mm:ss,SSS"

web:
  address: "0.0.0.0"
  port: 4000